@startuml er

object bots {
    + id : pk <<auto_increment>>
    --
    # user_id : fk
    * title : string
    * name : string
    * avatar : text
    * webhook : text
    * active : bool
    * created_at : datetime
    * updated_at : datetime
}

object post_messages {
    + id : pk <<auto_increment>>
    --
    # bot_id : fk
    * message : text
    * message_type : enum/string
    * sended : bool
    * created_at
    * updated_at
}

object sent_messages {
    + id : pk <<auto_increment>>
    --
    # post_message_id : fk
    * message : text
    * sended_at
}

object regular_timings {
    + id : pk <<auto_increment>>
    --
    # post_message_id : fk
    * day_of_week : enum/string
    * hour_time : time
}

object schedule_timings {
    + id : pk <<auto_increment>>
    --
    # post_message_id : fk
    * reservation_at : datetime
}


object admins {
    + id : pk <<auto_increment>>
    --
    * name : string
    * email : string
    * password : bytes
    * role : enum/string
    * created_at
    * updated_at
}

object users {
    + id : pk <<auto_increment>>
    --
    * email : string
    * password : bytes
    * active : boolean
    * created_at
    * updated_at
}

object activate_keys {
    + id : pk <<auto_increment>>
    --
    # user_id : fk unique
    * key : string unique
}

users ||--o| activate_keys
users ||--o{ bots
bots ||--o{ post_messages
post_messages ||--o{ regular_timings
post_messages ||--o| schedule_timings
post_messages ||--o{ sent_messages
@enduml
