app:
  name: "fiber"
  host: "127.0.0.1"
  port: 8000
  url: "http://127.0.0.1:8000"
  version: "0.0.1"
  env: "testing"
  secret: "secret"
  debug: false
  config: "./config"

server:
  prefork: false
  strict: false
  case: false
  etag: false
  bodylimit: 8
  concurrency: 256
  timeout:
    read: 60
    write: 60
    idle: 60
  buffer:
    read: 4
    write: 4

time:
  zone: "Asia/Tokyo"
  offset: 32400

db:
  type: "sqlite"
  host: "localhost"
  protocol: "tcp"
  name: "./fiber.sqlite?_foreign_keys=on"
  user: "root"
  pass: "root"
  port: 3306
  charset: "utf8mb4"
  collation: "utf8mb4_general_ci"
  connection:
    max: 10

log:
  server: "server.log"

file:
  storage: "storage"
  public: "public"
  current: ""

smtp:
  host: "127.0.0.1"
  port: 1025
  identity: ""
  user: ""
  pass: ""
  encryption: ""
  from:
    address: "fiber@xxx.com"
    name: "fiber"

static:
  prefix: "static"
  root: "static"
  index: "index.html"

template:
  path: "resource/view"
  suffix: ".html"
  reload: true

cache:
  expiration: 30
  control: false

session:
  type: "sqlite"
  expiration: 24
  name: "session"
  domain: ""
  path: "/"
  secure: false
  httponly: false
  sqlite:
    database: "./fiber.sqlite"
    table: "storage"
    reset: false
    interval: 100000000000

cors:
  origins: ["*"]
  maxage: 24
