@startuml model

object ボット {
    ラベル（識別名）
    ボット名
    アバター
    ウェブフックURL
    アクティブ
}
object 配信メッセージ {
    メッセージ内容
    配信タイプ
}
object 予約配信 {
    配信予定日時
}
object 定期配信 {
}
object 即時配信 {
}
object 定期タイミング {
    配信曜日
    配信時間
}
object 管理者 {
    アカウント名
    メールアドレス
    パスワード
}
object メッセージ配信 {
    配信済みメッセージ内容
    配信日時
}
object ロール {
    ロール名
}

ボット "1" -o "*" 配信メッセージ
配信メッセージ <|-- 即時配信
配信メッセージ <|-- 予約配信
配信メッセージ <|-- 定期配信
定期配信 "1" *-- "1..*" 定期タイミング
メッセージ配信 "*" --o "1" 配信メッセージ : 配信

管理者 "1" - "1" ロール

@enduml
