
@startuml model

object ボット {
    タイトル
    ウェブフックURL
}
object 配信メッセージ {
    メッセージ内容
}
object 配信タイプ {
    タイプ名
}
object 予約配信 {
    配信予定日時
}
object 定期配信 {
    配信曜日
    配信時間
}
object 即時配信 {
}
object 管理者 {
    アカウント名
    メールアドレス
    パスワード
}
object 配信履歴 {
    配信日時
}
object ロール {
    ロール名
}

配信メッセージ o-- ボット
配信メッセージ o-- 配信タイプ
配信タイプ <|-- 即時配信
配信タイプ <|-- 予約配信
配信タイプ <|-- 定期配信
配信履歴 o-- 配信メッセージ

管理者 o-- ロール

@enduml
