@startuml robustness-login

actor 管理者
boundary ログイン画面 #green
boundary ダッシュボード画面 #green
control ログイン画面を表示する
control 管理者アカウント情報を入力する
control メールアドレスの存在をチェックする
control メールアドレスが存在した管理者を取得する
control 取得した管理者のパスワード一致をチェックする
control エラーメッセージを表示する
control 取得した管理者の認証情報をセッションに保存する
entity 管理者アカウント #blue

管理者 --> ログイン画面
ログイン画面を表示する --> ログイン画面
ログイン画面 --> 管理者アカウント情報を入力する
管理者アカウント情報を入力する --> メールアドレスの存在をチェックする :ログインボタンを押す
メールアドレスの存在をチェックする --> エラーメッセージを表示する :メールアドレスが存在しない場合
メールアドレスの存在をチェックする --> メールアドレスが存在した管理者を取得する :メールアドレスが存在した場合
メールアドレスの存在をチェックする -- 管理者アカウント
メールアドレスが存在した管理者を取得する --> 取得した管理者のパスワード一致をチェックする
取得した管理者のパスワード一致をチェックする --> エラーメッセージを表示する :パスワードが一致しなかった場合
エラーメッセージを表示する --> ログイン画面
取得した管理者のパスワード一致をチェックする --> 取得した管理者の認証情報をセッションに保存する
取得した管理者のパスワード一致をチェックする -- 管理者アカウント
取得した管理者の認証情報をセッションに保存する --> ダッシュボード画面 :リダイレクト

@enduml
