@startuml robustness-post_message-create

actor 管理者
boundary ボット詳細画面 #green
boundary 即時配信追加画面 #green
boundary 定期配信追加画面 #green
boundary 予約配信追加画面 #green
boundary 404画面 #green
control ボット詳細画面を表示する
control ボット詳細を取得する
control 定期配信追加画面を表示する
control 即時配信追加画面を表示する
control 予約配信追加画面を表示する
control メッセージ内容を入力して配信日時を設定する
control メッセージ内容を入力する
control メッセージ内容を入力して定期タイミングを設定する
control 定期配信メッセージ内容の文字数をチェックする
control 即時配信メッセージ内容の文字数をチェックする
control 予約配信メッセージ内容の文字数をチェックする
control 配信日時と現在時間を比較チェックする
control 定期タイミングの曜日と時間の形式と重複をチェックする
control 定期配信関連のエラーメッセージを表示する
control 即時配信関連のエラーメッセージを表示する
control 予約配信関連のエラーメッセージを表示する
control 定期配信を追加する
control 定期タイミングを追加する
control 即時配信を追加する
control 予約配信を追加する
entity ボット #blue
entity 定期配信 #blue
entity 即時配信 #blue
entity 予約配信 #blue
entity 定期タイミング #blue

管理者 --> ボット詳細画面
ボット詳細画面を表示する --> ボット詳細を取得する
ボット詳細を取得する --> ボット詳細画面
ボット詳細を取得する --> 404画面 :ボットが見つからない
ボット -- ボット詳細を取得する
ボット詳細画面 --> 定期配信追加画面を表示する :定期配信ボタンを押す
ボット詳細画面 --> 即時配信追加画面を表示する :即時配信ボタンを押す
ボット詳細画面 --> 予約配信追加画面を表示する :予約配信ボタンを押す
定期配信追加画面を表示する --> 定期配信追加画面
即時配信追加画面を表示する --> 即時配信追加画面
予約配信追加画面を表示する --> 予約配信追加画面

定期配信追加画面 --> メッセージ内容を入力して定期タイミングを設定する
メッセージ内容を入力して定期タイミングを設定する --> 定期配信メッセージ内容の文字数をチェックする :追加ボタンを押す
定期配信メッセージ内容の文字数をチェックする --> 定期配信関連のエラーメッセージを表示する :文字数が2000文字以上だった場合
定期配信関連のエラーメッセージを表示する --> 定期配信追加画面を表示する
定期配信メッセージ内容の文字数をチェックする --> 定期タイミングの曜日と時間の形式と重複をチェックする
定期タイミングの曜日と時間の形式と重複をチェックする --> 定期配信関連のエラーメッセージを表示する :形式が不正または曜日と時間の組み合わせが重複していた場合
定期タイミングの曜日と時間の形式と重複をチェックする --> 定期配信を追加する
定期配信を追加する --> 定期タイミングを追加する
定期タイミングを追加する --> ボット詳細画面
定期配信を追加する -- 定期配信
定期タイミングを追加する -- 定期タイミング

即時配信追加画面 --> メッセージ内容を入力する
メッセージ内容を入力する --> 即時配信メッセージ内容の文字数をチェックする :追加ボタンを押す
即時配信メッセージ内容の文字数をチェックする --> 即時配信関連のエラーメッセージを表示する :文字数が2000文字以上だった場合
即時配信関連のエラーメッセージを表示する --> 即時配信追加画面
即時配信メッセージ内容の文字数をチェックする --> 即時配信を追加する
即時配信を追加する --> ボット詳細画面
即時配信を追加する -- 即時配信

予約配信追加画面 --> メッセージ内容を入力して配信日時を設定する
メッセージ内容を入力して配信日時を設定する --> 予約配信メッセージ内容の文字数をチェックする :追加ボタンを押す
予約配信メッセージ内容の文字数をチェックする --> 予約配信関連のエラーメッセージを表示する :文字数が2000文字以上だった場合
予約配信関連のエラーメッセージを表示する --> 予約配信追加画面
予約配信メッセージ内容の文字数をチェックする --> 配信日時と現在時間を比較チェックする
配信日時と現在時間を比較チェックする --> 予約配信関連のエラーメッセージを表示する :予約日時が現在時間よりも過去だった場合
配信日時と現在時間を比較チェックする --> 予約配信を追加する
予約配信を追加する -- 予約配信

@enduml
