@startuml usecase

left to right direction

:管理者:

rectangle メッセージスケジュール {
  usecase ボットを管理する
  usecase ボットを更新する
  usecase ボットを追加する
  usecase ボットを削除する
  usecase ボット一覧を見る
  usecase タイトルを入力する
  usecase ウェブフックURLを設定する

  usecase 配信メッセージを管理する
  usecase 配信メッセージを追加する
  usecase 即時配信メッセージを追加する
  usecase 定期配信メッセージを追加する
  usecase 予約配信メッセージを追加する
  usecase 配信メッセージを更新する
  usecase 配信メッセージを削除する
  usecase 配信メッセージ一覧を見る
  usecase メッセージ内容を入力する
  usecase 配信日時を選択する
  usecase 定期タイミングを追加する

  usecase 配信履歴を見る
}

rectangle アカウント管理 {
  usecase ログインする
  usecase 管理者を管理する
  usecase 管理者を追加する
  usecase 管理者を削除する
  usecase アカウント情報を入力する
  usecase ロールを設定する
}

管理者 -- ボットを管理する
ボットを管理する --> ボットを追加する
ボットを管理する --> ボットを更新する
ボットを管理する --> ボットを削除する
ボットを管理する --> ボット一覧を見る
ボットを追加する ..> タイトルを入力する #blue :invokes
ボットを追加する ..> ウェブフックURLを設定する #blue : invokes
ボットを更新する ..> タイトルを入力する #blue :invokes

管理者 -- 配信メッセージを管理する
配信メッセージを管理する --> 配信メッセージを追加する
配信メッセージを追加する <.. 即時配信メッセージを追加する :extend
配信メッセージを追加する <.. 定期配信メッセージを追加する :extend
配信メッセージを追加する <.. 予約配信メッセージを追加する :extend
配信メッセージを管理する --> 配信メッセージを更新する
配信メッセージを管理する --> 配信メッセージを削除する
配信メッセージを管理する --> 配信メッセージ一覧を見る
即時配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
定期配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
予約配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
予約配信メッセージを追加する ..> 配信日時を選択する #blue :invokes
定期配信メッセージを追加する ..> 定期タイミングを追加する #blue :invokes
配信メッセージを更新する ..> メッセージ内容を入力する #blue :invokes

管理者 -- 配信履歴を見る

管理者 -- ログインする
管理者 -- 管理者を管理する
管理者を管理する --> 管理者を追加する
管理者を管理する --> 管理者を削除する
管理者を追加する ..> アカウント情報を入力する #blue :invokes
管理者を追加する ..> ロールを設定する #blue :invokes

ログインする .> ボットを管理する #gray :precedes
ログインする .> 配信メッセージを管理する #gray :precedes
ログインする .> 配信履歴を見る #gray :precedes
ログインする .> 管理者を管理する #gray :precedes

@enduml
