@startuml model

object ボット {
    ボット名
    アバター
    ウェブフックURL
    アクティブ
    利用者ID
}
object 配信メッセージ {
    メッセージ内容
    配信タイプ
}
note right
=== 配信条件について
ボットがアクティブかつ
各配信の種類の時間的な条件が合えば
配信が可能となる
end note
object 予約配信 {
    配信予定日時
}
object 定期配信 {
    アクティブ
}
note left
=== アクティブについて
定期配信のみ
アクティブが有効な場合
配信が可能となる
end note
object 即時配信 {
}
object 定期タイミング {
    配信曜日
    配信時間
}
object Api配信 {
    最終配信メッセージ
    Apiアクセスキー
}
note bottom
=== Apiアクセスキーについて
Apiアクセスの時に
このキーが一致しない場合は配信できない
end note
object 管理者 {
    アカウント名
    メールアドレス
    パスワード
}
object メッセージ配信 {
    配信済みメッセージ内容
    配信日時
}
object ロール {
    ロール名
}
object 利用者 {
    メールアドレス
    パスワード
    アクティブ
}
note bottom
=== アクティブについて
アクティブな場合にのみ
ログインできる
利用者は利用者登録後
メールに記載されたキー付きURLにアクセスし
キーが一致したらアクティブにする
end note
object アクティベーションキー {
    キー
}

アクティベーションキー "0..1" --* "1" 利用者
利用者 "1" o- "*" ボット
ボット "1" -o "*" 配信メッセージ
配信メッセージ <|-- 即時配信
配信メッセージ <|-- 予約配信
配信メッセージ <|-- 定期配信
配信メッセージ <|-- Api配信
定期配信 "1" *-- "1..*" 定期タイミング
メッセージ配信 "*" --o "1" 配信メッセージ : 配信

管理者 "1" *- "1" ロール

@enduml
