@startuml usecase

left to right direction

:管理者:
:利用者:
:定期処理システム:

rectangle ボットシステム {
    usecase ボットを管理する
    usecase ボットを更新する
    usecase ボットを追加する
    usecase ボットを削除する
    usecase ボットのアクティブ状態を変更する
    usecase ボット一覧を見る
    usecase タイトルを入力する
    usecase ウェブフックURLを設定する
    usecase アクティブ状態を設定する
}
rectangle メッセージシステム {
    usecase 配信メッセージを管理する
    usecase 配信メッセージを追加する
    usecase 即時配信メッセージを追加する
    usecase 定期配信メッセージを追加する
    usecase 予約配信メッセージを追加する
    usecase Api配信メッセージを追加する
    usecase 配信メッセージを更新する
    usecase 配信メッセージを削除する
    usecase 配信メッセージ一覧を見る
    usecase メッセージ内容を入力する
    usecase 配信日時を選択する
    usecase 定期タイミングを追加する
    usecase Apiキーを生成する

    usecase 配信履歴を見る

    usecase メッセージ配信をする
}

rectangle 管理者システム {
    usecase 管理者を管理する
    usecase 管理者を追加する
    usecase 管理者を削除する
    usecase 管理者アカウント情報を入力する
    usecase ロールを設定する
}

rectangle 利用者システム {
    usecase 利用者を管理する
    usecase 利用者を追加する
    usecase 利用者を削除する
    usecase 利用者アカウント情報を入力する
}

rectangle 管理者認証システム {
    usecase 管理者ツールへログインする
    usecase 管理者ツールからログアウトする
}

rectangle 利用者認証システム {
    usecase 利用者登録をする
    usecase メールによる本人確認をする

    usecase 利用者ツールへログインする
    usecase 利用者ツールからログアウトする
}

管理者 -- ボットを管理する
利用者 -- ボットを管理する
ボットを管理する --> ボットを追加する
ボットを管理する --> ボットを更新する
ボットを管理する --> ボットを削除する
ボットを管理する --> ボット一覧を見る
ボットを管理する --> ボットのアクティブ状態を変更する
ボットを追加する ..> タイトルを入力する #blue :invokes
ボットを追加する ..> ウェブフックURLを設定する #blue : invokes
ボットを更新する ..> タイトルを入力する #blue :invokes
ボットを更新する ..> アクティブ状態を設定する #blue :invokes
ボットのアクティブ状態を変更する ..> アクティブ状態を設定する #blue :invokes

管理者 -- 配信メッセージを管理する
利用者 -- 配信メッセージを管理する
配信メッセージを管理する --> 配信メッセージを追加する
配信メッセージを追加する <.. 即時配信メッセージを追加する :extend
配信メッセージを追加する <.. 定期配信メッセージを追加する :extend
配信メッセージを追加する <.. 予約配信メッセージを追加する :extend
配信メッセージを追加する <.. Api配信メッセージを追加する :extend
配信メッセージを管理する --> 配信メッセージを更新する
配信メッセージを管理する --> 配信メッセージを削除する
配信メッセージを管理する --> 配信メッセージ一覧を見る
即時配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
定期配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
予約配信メッセージを追加する ..> メッセージ内容を入力する #blue :invokes
予約配信メッセージを追加する ..> 配信日時を選択する #blue :invokes
定期配信メッセージを追加する ..> 定期タイミングを追加する #blue :invokes
配信メッセージを更新する ..> メッセージ内容を入力する #blue :invokes
Api配信メッセージを追加する ..> Apiキーを生成する #blue :invokes

管理者 -- 配信履歴を見る
利用者 -- 配信履歴を見る

管理者 -- 管理者ツールへログインする
管理者 -- 管理者ツールからログアウトする

管理者 -- 管理者を管理する
管理者を管理する --> 管理者を追加する
管理者を管理する --> 管理者を削除する
管理者を追加する ..> 管理者アカウント情報を入力する #blue :invokes
管理者を追加する ..> ロールを設定する #blue :invokes

管理者 -- 利用者を管理する
利用者を管理する --> 利用者を追加する
利用者を管理する --> 利用者を削除する
利用者を追加する ..> 利用者アカウント情報を入力する #blue :invokes

利用者 -- 利用者登録をする
利用者登録をする --> メールによる本人確認をする
利用者 -- 利用者ツールへログインする
利用者 -- 利用者ツールからログアウトする


管理者ツールへログインする .> ボットを管理する #gray :precedes
管理者ツールへログインする .> 配信メッセージを管理する #gray :precedes
管理者ツールへログインする .> 配信履歴を見る #gray :precedes
管理者ツールへログインする .> 管理者を管理する #gray :precedes

利用者ツールへログインする .> ボットを管理する #gray :precedes
利用者ツールへログインする .> 配信メッセージを管理する #gray :precedes
利用者ツールへログインする .> 配信履歴を見る #gray :precedes

即時配信メッセージを追加する -- メッセージ配信をする
メッセージ配信をする -- 定期処理システム

@enduml
