name: ManualTestAndDeploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Deploy Branch'
        required: true
        default: 'develop'

env:
  BINARY_DIRECTORY: 'bin'
  DEPLOY_DIRECTORY: '/var/app/dc-scheduler'
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.branch }}
        if: ${{ github.event.inputs.branch != '' }}

      - name: SetUp Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Dependency
        run: go get -v -t -d ./...

      - name: Run TestCode
        run: go test -v ./test

  deploy:
    name: Deploy
    needs: testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.branch }}
        if: ${{ github.event.inputs.branch != '' }}

      - name: SetUp Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go
        run: |
          mkdir -p ./${{ env.BINARY_DIRECTORY }}
          go build --ldflags '-extldflags "-static"' -a -o ./${{ env.BINARY_DIRECTORY }}/linux-app ./main.go
          go build --ldflags '-extldflags "-static"' -a -o ./${{ env.BINARY_DIRECTORY }}/linux-app-cli ./cli/main.go

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          source: './${{ env.BINARY_DIRECTORY }}/linux-app,./${{ env.BINARY_DIRECTORY }}/linux-app-cli'
          target: ${{ env.DEPLOY_DIRECTORY }}/

  preparation:
    name: Preparation
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            mkdir -p ./${{ env.BINARY_DIRECTORY }}
            git fetch origin
            git reset --hard origin/${{ github.event.inputs.branch }}
            ${{ env.DEPLOY_DIRECTORY }}/${{ env.BINARY_DIRECTORY }}/linux-app-cli migrate:auto

      - name: Echo DeployBranch
        run: |
          echo "DeployBranch: ${{ github.event.inputs.branch }}"
