on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Deploy Branch"
        required: true
        default: "develop"

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SetUp Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Dependency
        run: go get -v -t -d ./...

      - name: Run TestCode
        run: go test -v ./test

  deploy:
    name: Deploy
    needs: testing
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.branch }}"
